steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-repo/train:wconfig',
    '-f',
    'dockerfiles/cloudtrain.dockerfile'
  ]
  
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-repo/train:wconfig'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
