
model:
  model_name: "mobilenetv3_small_100"
  pretrained: true
  num_classes: 10

data:
  processed_dir: data/processed
  raw_dir: data/raw

data_loader:
  _target_: data.OracleMNISTModuleBasic
  batch_size: 32
  num_workers: 4
  in_memory_dataset: false
  validation_split: 0.2
  img_size: 28
  use_rgb: true

train:
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0
  scheduler:
    _target_: scheduler.sarphiv_scheduler.SarphivSchedular
    lr_half_period: 2000
    lr_mult_period: 2
    lr_min: 1e-4
    lr_warmup_max: 4e-2
    lr_warmup_period: 1000
  batch_size: 32
  epochs: 10

misc:
  seed: 42