method: random
metric:
  name: val_acc
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.01
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [6, 7, 8]
    values: [8, 10, 12]
