method: random
metric:
  name: val_acc
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.01
  batch_size:
    values: [16, 32, 64]
  model_name:
    values: ["mobilenetv3_small_100", "resnet18", "efficientnet_b0"]
